site_name: "Netzwerk Workshop"
theme: material
dev_addr: "0.0.0.0:8080"
site_url: https://netzwerk-workshop.rebsamen.net

plugins: 
  - search



markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences