site_name: "Netzwerk Workshop"
theme: material
dev_addr: "127.0.0.1:8080"

site_url: https://netzwerk-workshop.rebsamen.net

plugins:
  - search
  - callouts

markdown_extensions:
  - nl2br
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - tables
