name: Create Build in Public
run-name: Build gets pushed to public on tagging
on:
  push:
    branches: [main]

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set Python environment
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"
          cache: "pip"
      - name: Build Code
        working-directory: mkdocs
        run: mkdocs build
      - name: Push to Release
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: release
          FOLDER: mkdocs/site
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
